#
# Connection
#
broker: !secret MQTTHostname
port: !secret MQTTPort
certificate: /secrets/TLS/MQTT/CA.pem
#
# Credentials
#
username: !secret MQTTUsername
password: !secret MQTTPassword

discovery: true
# username: !secret mqtt_username
# password: !secret mqtt_password